CREATE TABLE [dbo].[Accounts_History]
(
    [Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
    [AccountId] BIGINT NOT NULL DEFAULT 0,
    [Type] TINYINT NOT NULL DEFAULT 0 ,
    [OtherAccountId] BIGINT NOT NULL DEFAULT 0,
    [TargetId] BIGINT NOT NULL DEFAULT 0,
    [TargetPostId] BIGINT NOT NULL DEFAULT 0,
    [TargetCommentId] BIGINT NOT NULL DEFAULT 0,
    [CreatedTime] DATETIMEOFFSET NOT NULL DEFAULT '1900-01-01 00:00:00 +00:00',
)