CREATE TABLE [dbo].[Characters]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
    [MoaRef] NVARCHAR(50) NOT NULL UNIQUE,
    [BlizzardId] BIGINT NOT NULL DEFAULT 0,
    [Name] NVARCHAR(50) NOT NULL,
    [SearchableName] NVARCHAR(50) NOT NULL,
    [RegionId] TINYINT NOT NULL DEFAULT 0,
    [AccountId] BIGINT NOT NULL DEFAULT 0 ,
    [AccountSync] TINYINT NOT NULL DEFAULT 0,
    [RealmId] INT NOT NULL DEFAULT 0 ,
    [Class] TINYINT NOT NULL DEFAULT 0,
    [Gender] TINYINT NOT NULL DEFAULT 0,
    [Race] TINYINT NOT NULL DEFAULT 0,
    [Level] TINYINT NOT NULL DEFAULT 0,
    [Faction] TINYINT NOT NULL DEFAULT 0,
    [AvatarLink] NVARCHAR(100) NULL,
    [AchievementTotalQuantity] INT NOT NULL DEFAULT 0,
    [AchievementTotalPoints] INT NOT NULL DEFAULT 0,
    [GuildId] BIGINT NOT NULL DEFAULT 0,
    [GuildName] NVARCHAR(50) NULL,
    [GuildRef] NVARCHAR(75) NULL,
    [GuildRank] TINYINT NOT NULL DEFAULT 0,
    [LastUpdateEndTime] DATETIMEOFFSET NOT NULL DEFAULT '1900-01-01 00:00:00 +00:00',
    [LastUpdateResult] TINYINT NOT NULL DEFAULT 0,
    [LastUpdateHttpResult] SMALLINT NOT NULL DEFAULT 0,
    [BlizzardProfileLastModified] BIGINT NOT NULL DEFAULT 0,
    [BlizzardAchievementsLastModified] BIGINT NOT NULL DEFAULT 0,
    [BlizzardRendersLastModified] BIGINT NOT NULL DEFAULT 0,
 )

GO CREATE INDEX [IX_Characters_Ref] ON [dbo].[Characters] ([MoaRef])