CREATE TABLE [dbo].[Posts_Comments_Reactions]
(
    [Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
    [AccountId] BIGINT NOT NULL DEFAULT 0 ,
    [CommentId] BIGINT NOT NULL DEFAULT 0 ,
    [Reaction] TINYINT NOT NULL DEFAULT 0,
    [LastUpdateTime]  DATETIMEOFFSET NOT NULL DEFAULT '1900-01-01 00:00:00 +00:00',
)