CREATE TABLE [dbo].[Tags]
(
    [Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
    [MoaRef] NVARCHAR(50) NOT NULL UNIQUE,
    [TotalCount] BIGINT NOT NULL DEFAULT 0,
    [CreatedTime] DATETIMEOFFSET NOT NULL DEFAULT '1900-01-01 00:00:00 +00:00',
)