<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>..\..\AzerothMemories.Build\$(Configuration)\$(AssemblyName)</OutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <ServerGarbageCollection>true</ServerGarbageCollection>
    </PropertyGroup>
  
    <ItemGroup>
      <Compile Include="..\..\AzerothMemories.X-DoNotCommit\CommonConfigDoNotCommit.cs" Link="Common\CommonConfigDoNotCommit.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Storage.Blobs" Version="12.23.0" />
        <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="9.0.8" />
        <PackageReference Include="MemoryPack.Generator" Version="1.21.4" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="9.0.2" />
        <PackageReference Include="MudBlazor" Version="8.3.0" />
        <PackageReference Include="NetEscapades.AspNetCore.SecurityHeaders" Version="0.24.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime" Version="9.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.6" />
        <PackageReference Include="ActualLab.Fusion.EntityFramework.Npgsql" Version="9.8.46" />
        <PackageReference Include="ActualLab.Fusion.Server" Version="9.8.46" />
        <PackageReference Include="ActualLab.Generators" Version="9.8.46" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
        <PackageReference Include="AspNet.Security.OAuth.BattleNet" Version="9.0.0" />
        <PackageReference Include="AspNet.Security.OAuth.Patreon" Version="9.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\AzerothMemories.WebBlazor\AzerothMemories.WebBlazor\AzerothMemories.WebBlazor.csproj" />
    </ItemGroup>

</Project>