global using AzerothMemories.WebBlazor.Blizzard;
global using AzerothMemories.WebBlazor.Common;
global using AzerothMemories.WebBlazor.Services.Commands;
global using AzerothMemories.WebBlazor.ViewModels;
global using AzerothMemories.WebServer.Common;
global using AzerothMemories.WebServer.Database;
global using AzerothMemories.WebServer.Database.Records;
global using AzerothMemories.WebServer.Services;
global using Microsoft.EntityFrameworkCore;
global using NodaTime;
global using Stl.CommandR;
global using Stl.Fusion;
global using Stl.Fusion.Authentication;
global using SystemClock = NodaTime.SystemClock;