<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>..\..\AzerothMemories.Build\$(Configuration)\$(AssemblyName)</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions" Version="9.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.6" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\AzerothMemories.WebServer\AzerothMemories.WebServer\AzerothMemories.WebServer.csproj" />
    </ItemGroup>

</Project>
